# Generated by Django 5.2.5 on 2025-08-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionVeterinaria_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativo',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Administrativo', 'verbose_name_plural': 'Administrativos'},
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'permissions': [('manage_all_appointments', 'Puede gestionar todas las citas')], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='historialmedico',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Historial médico', 'verbose_name_plural': 'Historiales médicos'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'permissions': [('view_health_stats', 'Puede ver estadísticas de salud'), ('export_reports', 'Puede exportar reportes')], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='propietario',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Propietario', 'verbose_name_plural': 'Propietarios'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Usuario (dominio)', 'verbose_name_plural': 'Usuarios (dominio)'},
        ),
        migrations.AlterModelOptions(
            name='veterinario',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Veterinario', 'verbose_name_plural': 'Veterinarios'},
        ),
    ]
