# Generated by Django 5.2.5 on 2025-08-14 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionVeterinaria_app', '0002_alter_administrativo_options_alter_cita_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinario',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario del sistema asociado a este veterinario (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_veterinario', to=settings.AUTH_USER_MODEL),
        ),
    ]
