# Generated by Django 5.2.5 on 2025-08-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionVeterinaria_app', '0003_veterinario_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['fecha_hora'], 'permissions': [('manage_all_appointments', 'Puede gestionar todas las citas')], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AddField(
            model_name='cita',
            name='duracion_min',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('atendida', 'Atendida')], default='pendiente', max_length=12),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['veterinario', 'fecha_hora'], name='GestionVete_veterin_7fab1e_idx'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.CheckConstraint(condition=models.Q(('duracion_min__gt', 0)), name='cita_duracion_positiva'),
        ),
    ]
