# Generated by Django 5.2.5 on 2025-08-16 05:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionVeterinaria_app', '0004_alter_cita_options_cita_duracion_min_cita_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
