# Generated by Django 5.2.5 on 2025-08-16 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionVeterinaria_app', '0005_cita_created_at_paciente_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmedico',
            name='cita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atencion', to='GestionVeterinaria_app.cita'),
        ),
    ]
