# Generated by Django 5.2.5 on 2025-08-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionVeterinaria_app', '0006_historialmedico_cita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='cita',
            name='cita_duracion_positiva',
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='GestionVete_veterin_7fab1e_idx',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='duracion_min',
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], default='programada', max_length=12),
        ),
    ]
