# Generated by Django 5.2.5 on 2025-08-21 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionVeterinaria_app', '0007_alter_cita_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
